#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.13f1_d4ddf0d95db9"
#define UNITY_VERSION_FULL_NICE "2019.3.13f1 (d4ddf0d95db9)"
#define UNITY_VERSION_BLD 13950448
#define UNITY_VERSION_DATE 1588614178
#define UNITY_VERSION_WIN "2019.3.13.13950448"
#define UNITY_VERSION_BRANCH "2019.3/release"
